spring:
  application:
    name: university
  datasource:
    url: jdbc:mysql://localhost:3306/university?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    show-sql: false
  cache:
    cache-names:
      - students
      - studentById
      - lecturers
      - lecturerById
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10s
logging:
  level:
    root: INFO
    com.acme.university: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"